name: Debug (by PSModule)
description: |
  Print info from the runner environment to logs.
  Uses all the contexts and environment variables.
  - [Contexts | GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/contexts)
  - [Variables] | GitHub Docs](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)
author: PSModule
branding:
  icon: clipboard
  color: gray

inputs:
  working-directory:
    description: The working directory where the action will be executed
    required: false

runs:
  using: composite
  steps:
    - name: Debug
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_ENV: ${{ toJson(env) }}
        CONTEXT_VARS: ${{ inputs.vars }}
        CONTEXT_JOB: ${{ toJson(job) }}
        # CONTEXT_JOBS: ${{ toJson(jobs) }}
        CONTEXT_STEPS: ${{ toJson(steps) }}
        CONTEXT_RUNNER: ${{ toJson(runner) }}
        # CONTEXT_SECRETS: ${{ toJson(secrets) }}
        CONTEXT_STRATEGY: ${{ toJson(strategy) }}
        CONTEXT_MATRIX: ${{ toJson(matrix) }}
        # CONTEXT_NEEDS: ${{ toJson(needs) }}
        CONTEXT_INPUTS: ${{ toJson(inputs) }}
      run: |
        # Debug environment
        . "$GITHUB_ACTION_PATH/scripts/main.ps1" -Verbose
