name: Debug (by PSModule)
description: |
  Print info from the runner environment to logs.
author: PSModule
branding:
  icon: clipboard
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Debug
      uses: PSModule/GitHub-Script@v1
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_ENV: ${{ toJson(env) }}
        # CONTEXT_VARS: ${{ toJson(vars) }}
        CONTEXT_JOB: ${{ toJson(job) }}
        # CONTEXT_JOBS: ${{ toJson(jobs) }}
        CONTEXT_STEPS: ${{ toJson(steps) }}
        CONTEXT_RUNNER: ${{ toJson(runner) }}
        # CONTEXT_SECRETS: ${{ toJson(secrets) }}
        CONTEXT_STRATEGY: ${{ toJson(strategy) }}
        CONTEXT_MATRIX: ${{ toJson(matrix) }}
        # CONTEXT_NEEDS: ${{ toJson(needs) }}
        CONTEXT_INPUTS: ${{ toJson(inputs) }}
      with:
        Debug: true
        Verbose: true
        Script: |
          # Debug environment
          . "${{ github.action_path }}\scripts\main.ps1" -Verbose
