name: Debug (by PSModule)
description: |
  Print info from the runner environment to logs.
author: PSModule
branding:
  icon: clipboard
  color: gray-dark

inputs:
  Token:
    description: The GitHub token to use for authentication.
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Debug
      uses: PSModule/GitHub-Script@0097f3bbe3f413f3b577b9bcc600727b0ca3201a # v1.7.10
      env:
        GITHUB_TOKEN: ${{ inputs.Token }}
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_ENV: ${{ toJson(env) }}
        # CONTEXT_VARS: ${{ toJson(vars) }}
        CONTEXT_JOB: ${{ toJson(job) }}
        # CONTEXT_JOBS: ${{ toJson(jobs) }}
        CONTEXT_STEPS: ${{ toJson(steps) }}
        CONTEXT_RUNNER: ${{ toJson(runner) }}
        # CONTEXT_SECRETS: ${{ toJson(secrets) }}
        CONTEXT_STRATEGY: ${{ toJson(strategy) }}
        CONTEXT_MATRIX: ${{ toJson(matrix) }}
        # CONTEXT_NEEDS: ${{ toJson(needs) }}
        CONTEXT_INPUTS: ${{ toJson(inputs) }}
      with:
        Name: Debug
        Script: |
          # Debug environment
          ${{ github.action_path }}/src/main.ps1
