name: Debug (by PSModule)
description: |
  Print info from the runner environment to logs.
author: PSModule
branding:
  icon: clipboard
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Install GitHub
      shell: pwsh
      run: |
        # Install GitHub
        $params = @{
          Name            = 'GitHub'
          Repository      = 'PSGallery'
          TrustRepository = $true
          Verbose         = $true
        }
        Install-PSResource @params
        Import-Module -Name 'GitHub' -Force -Verbose

    - name: Debug
      shell: pwsh
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_ENV: ${{ toJson(env) }}
        # CONTEXT_VARS: ${{ toJson(vars) }}
        CONTEXT_JOB: ${{ toJson(job) }}
        # CONTEXT_JOBS: ${{ toJson(jobs) }}
        CONTEXT_STEPS: ${{ toJson(steps) }}
        CONTEXT_RUNNER: ${{ toJson(runner) }}
        # CONTEXT_SECRETS: ${{ toJson(secrets) }}
        CONTEXT_STRATEGY: ${{ toJson(strategy) }}
        CONTEXT_MATRIX: ${{ toJson(matrix) }}
        # CONTEXT_NEEDS: ${{ toJson(needs) }}
        CONTEXT_INPUTS: ${{ toJson(inputs) }}
      run: |
        # Debug environment
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
